### ISSUE TITLE
Господа! Как получить figi коды по средствам имени тикера? [Issue] 

### ISSUE THREAD

**Issue by sneakybeaky18** [Tinkoff/invest-python#36]
### Что случилось?

Казалось бы, задача простая, но перерыв с десяток методов не нашел решения. Даже openfigi api пробовал, не помогло. В общем, как можно замапить тикер и получить figi по средствам invest-python?  

### Воспроизведение

Не работает:

```
from openapi_client import openapi

client = openapi.api_client(TOKEN)
instr = client.market.market_search_by_ticker_get('AAPL' ) 
print(instr)
```

```
import requests

response = requests.post(url='https://api.openfigi.com/v3/search/',
                        headers={'Content-Type': 'text/json'},
                        json={
                            'query': 'AAPL',
                            'exchCode': 'GM'
                        })
                        
APPLE_FIGI = response.json()['data'][0]['figi']

async def main():
    global APPLE_FIGI
    async with ti.Streaming(TOKEN) as streaming:
        await streaming.candle.subscribe(APPLE_FIGI, ti.CandleResolution.min5) 
        async for event in streaming:
            print(event)

```

```
from tinkoff.investments import TinkoffInvestmentsRESTClient

async def main():
    client = TinkoffInvestmentsRESTClient(token=TOKEN)
    instruments = await client.market.instruments.search('AAPL')
    for instrument in instruments:
        print(instrument.figi)

asyncio.run(main())

```

### Tinkoff Invest Version

0.2.0-beta19

### Python Version

3.9

### OS

Windows

### Логи

```shell
Первый метод выдает 403, второй метод выдает что такой Figi не найден. 

Третий метод выдает длинный лог, суть которого как я понял в том, что в запрос передается некорректный mime type

Traceback (most recent call last):
  File "C:\Users\kgera\Desktop\tin api\main.py", line 65, in <module>
    asyncio.run(main())
  File "C:\Users\kgera\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kgera\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\kgera\Desktop\tin api\main.py", line 61, in main
    instruments = await client.market.instruments.search('AAPL')
  File "C:\Users\kgera\anaconda3\lib\site-packages\tinkoff\investments\api\market.py", line 26, in search
    return await self.__get_instruments(
  File "C:\Users\kgera\anaconda3\lib\site-packages\tinkoff\investments\api\market.py", line 59, in __get_instruments
    payload = await self._request(
  File "C:\Users\kgera\anaconda3\lib\site-packages\tinkoff\investments\api\base.py", line 25, in _request
    data = await self._client._request(method, path, rate_limit, **kwargs)
  File "C:\Users\kgera\anaconda3\lib\site-packages\tinkoff\investments\client\rest.py", line 63, in _request
    return await response.json()
  File "C:\Users\kgera\anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('https://api-invest.tinkoff.ru/openapi/market/search/by-ticker?ticker=AAPL')
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A604162C10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001A6041B47C0>, 34763.546)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001A604162460>
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001A604162BB0>
transport: <_ProactorSocketTransport fd=664 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\kgera\anaconda3\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "C:\Users\kgera\anaconda3\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x000001A602FE65E0>
Traceback (most recent call last):
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 321, in __del__
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 316, in close
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "C:\Users\kgera\anaconda3\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "C:\Users\kgera\anaconda3\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "C:\Users\kgera\anaconda3\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Users\kgera\anaconda3\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by dsenash** [comment]
with Client(TOKEN) as client:
        response = client.instruments.get_instrument_by(id_type=2,class_code="SPBXM",id=ticker)

Это работает, но для тикера нужен class_code. Это неудобно. Я короче качнул все тикеры в CSV и беру фиги из нее. Так проще.

**Comment by sneakybeaky18** [comment]
> with Client(TOKEN) as client: response = client.instruments.get_instrument_by(id_type=2,class_code="SPBXM",id=ticker)
> 
> Это работает, но для тикера нужен class_code. Это неудобно. Я короче качнул все тикеры в CSV и беру фиги из нее. Так проще.

Спасибо за информацию! А откуда качнул то?

**Comment by sneakybeaky18** [comment]
Господа! Есть решение, на платформе https://www.openfigi.com можно найти интересующий вас актив следующим нехитрым образом: указываете название компании, жмете на кнопку **search** или же **поиск**. Далее, в фильтрах в разделе **Ticker** пишите непосредственно тикер интересующий вас компании. Допустим, это будет SBER. По итогу получаем список так называемых кандидатов. А дальше самое интересное: нужно понять, какой Exchange Code вас интересует. Опытным путем было выяснено, что для RU акций актуальный Exchange это RM. Пишите RM и далее вы видите результат в виде следующего Figi кода: [BBG004730N88](https://www.openfigi.com/id/BBG004730N88). Выводы делайте самостоятельно.

**Comment by dsenash** [comment]
> > with Client(TOKEN) as client: response = client.instruments.get_instrument_by(id_type=2,class_code="SPBXM",id=ticker)
> > Это работает, но для тикера нужен class_code. Это неудобно. Я короче качнул все тикеры в CSV и беру фиги из нее. Так проще.
> 
> Спасибо за информацию! А откуда качнул то?

Из Тинька конечно.
with Client(TOKEN) as client:
        response = client.instruments.shares(instrument_status=0)
