### ISSUE TITLE
SubscribeOrderBookRequest выдает ошибку

### ISSUE THREAD

**Issue by dsenash** [Tinkoff/invest-python#37]
### Что случилось?

Пытаюсь подключиться строимом к стакану.

```python
def request_iterator():
        yield MarketDataRequest(
            subscribe_order_book_request=SubscribeOrderBookRequest(
                subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                instruments=[
                    OrderBookInstrument(
                        figi="BBG000BH5LT6",
                        depth=10,
                    )
                ],
            )
        )
```

Получаю:
None MarketDataStream UNKNOWN Exception iterating requests!

### Tinkoff Invest Version

0.2.0-beta19

### Python Version

3.9

### OS

Linux

### Логи

```shell
Traceback (most recent call last):
  File "/home/cust/.local/lib/python3.8/site-packages/tinkoff/invest/_errors.py", line 43, in wrapper
    yield from func(*args, **kwargs)
  File "/home/cust/.local/lib/python3.8/site-packages/tinkoff/invest/services.py", line 600, in market_data_stream
    for response in self.stub.MarketDataStream(
  File "/home/cust/.local/lib/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/home/cust/.local/lib/python3.8/site-packages/grpc/_channel.py", line 809, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "robot_1.py", line 220, in <module>
    orderbook(figi)
  File "robot_1.py", line 121, in orderbook
    for marketdata in client.market_data_stream.market_data_stream(
  File "/home/cust/.local/lib/python3.8/site-packages/tinkoff/invest/_errors.py", line 53, in wrapper
    raise RequestError(
tinkoff.invest.exceptions.RequestError: (<StatusCode.UNKNOWN: (2, 'unknown')>, 'Exception iterating requests!', None)
```

**Comment by daxartio** [comment]
Итератор не завершается?

**Comment by daxartio** [comment]
Этот апи не пробовали?
https://github.com/Tinkoff/invest-python/blob/main/examples/easy_stream_client.py

**Comment by dsenash** [comment]
Candle работает. А вот свечи нет. Хотя выглядит все правильно.

**Comment by daxartio** [comment]
Дэк, итератор завершается?

**Comment by dsenash** [comment]
Заработало. Проблема в целом в отсутствии доки по SDK. Тяжело искать кошку в темной комнате не понимая как она должна выглядеть.
Спасибо.
