### ISSUE TITLE
[Bug]  trades_stream() -> AttributeError: accounts

### ISSUE THREAD

**Issue by HappyManRus** [Tinkoff/invest-python#52]
### Что случилось?

После обновления с 19 на 23 бетту возникли проблемы с client.orders_stream.trades_stream()
Понижение версии восстанавливает работу кода.

### Воспроизведение

    async with AsyncClient(TOKEN) as client:
            async for tradesdata in client.orders_stream.trades_stream():
                await queue.put(tradesdata)
                await asyncio.sleep(0.5)

### Tinkoff Invest Version

0.2.0-beta23

### Python Version

3.9

### OS

Windows

### Логи

```shell
11:18:09: default_exception_handler: Task exception was never retrieved
future: <Task finished name='Task-2' coro=<TradesData() done, defined at c:\Users\LLLL\Dropbox\Docs\Coding\kkkk\tinkof_new_sdk_stream_v11.py:106> exception=AttributeError('accounts')>
Traceback (most recent call last):
  File "c:\Users\LLLL\Dropbox\Docs\Coding\kkkk\tinkof_new_sdk_stream_v11.py", line 109, in TradesData
    async for tradesdata in client.orders_stream.trades_stream():
  File "c:\Users\LLLL\Dropbox\Docs\Coding\kkkk\.venv\lib\site-packages\tinkoff\invest\_errors.py", line 91, in wrapper
    async for result in func(*args, **kwargs):
  File "c:\Users\LLLL\Dropbox\Docs\Coding\kkkk\.venv\lib\site-packages\tinkoff\invest\async_services.py", line 887, in trades_stream
    request=_grpc_helpers.dataclass_to_protobuff(
  File "c:\Users\LLLL\Dropbox\Docs\Coding\kkkk\.venv\lib\site-packages\tinkoff\invest\_grpc_helpers.py", line 324, in dataclass_to_protobuff
    pb_value = getattr(protobuff_obj, field_name)
AttributeError: accounts
```

**Comment by irusland** [comment]
#54
