### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'dateutil'

### ISSUE THREAD

**Issue by pashkatrick** [Tinkoff/invest-python#65]
### Что случилось?

1. скопировал пример

```python
from tinkoff.invest import Client

TOKEN = 'token'

with Client(TOKEN) as client:
    print(client.users.get_accounts())
```
2. подставляю sandbox token
3. запускаю

### Tinkoff Invest Version

0.2.0-beta26

### Python Version

3.10

### OS

Mac OS (m1)

### Логи

```shell
Traceback (most recent call last):
  File "/Users/pudins/Desktop/ne_tinkoff/test.py", line 1, in <module>
    from tinkoff.invest import Client
  File "/Users/pudins/Desktop/ne_tinkoff/venv/lib/python3.10/site-packages/tinkoff/invest/__init__.py", line 1, in <module>
    from .clients import AsyncClient, Client
  File "/Users/pudins/Desktop/ne_tinkoff/venv/lib/python3.10/site-packages/tinkoff/invest/clients.py", line 3, in <module>
    from .async_services import AsyncServices
  File "/Users/pudins/Desktop/ne_tinkoff/venv/lib/python3.10/site-packages/tinkoff/invest/async_services.py", line 137, in <module>
    from .utils import get_intervals, now
  File "/Users/pudins/Desktop/ne_tinkoff/venv/lib/python3.10/site-packages/tinkoff/invest/utils.py", line 7, in <module>
    import dateutil.parser  # noqa:  I900 'dateutil' not listed as a requirement
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by irusland** [comment]
https://github.com/Tinkoff/invest-python/pull/66

**Comment by daxartio** [comment]
Fixed 0.2.0-beta27
