### ISSUE TITLE
[Bug]  Ошибка при подписки на свечи,  разница между версиями beta28 и beta29 

### ISSUE THREAD

**Issue by tezrik** [Tinkoff/invest-python#76]
### Что случилось?

При подписке на свечи через Client возникает ошибка. 
Я понимаю что это бетта версии апи, но думаю должна быть обратная совместимость. либо какие-то дефолтные значения для таких параметров.  Либо обновлять примеры кода. 

### Воспроизведение

Отправить запрос без waiting_close,

 yield MarketDataRequest(
                    subscribe_candles_request=SubscribeCandlesRequest(
                        subscription_action=SubscriptionAction.SUBSCRIPTION_ACTION_SUBSCRIBE,
                        instruments=instruments_subscribe,
                    )
                )

### Tinkoff Invest Version

0.2.0-beta29

### Python Version

3.10

### OS

Linux

### Логи

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/grpc/aio/_call.py", line 406, in _consume_request_iterator
    async for request in request_iterator:
  File "/usr/local/lib/python3.10/site-packages/tinkoff/invest/async_services.py", line 734, in _convert_market_data_stream_request
    yield _grpc_helpers.dataclass_to_protobuff(
  File "/usr/local/lib/python3.10/site-packages/tinkoff/invest/_grpc_helpers.py", line 314, in dataclass_to_protobuff
    dataclass_to_protobuff(field_value, pb_value)
  File "/usr/local/lib/python3.10/site-packages/tinkoff/invest/_grpc_helpers.py", line 303, in dataclass_to_protobuff
    setattr(protobuff_obj, field_name, field_value)
TypeError: <object object at 0x7fe0a4904ae0> has type object, but expected one of: int, bool
```

**Comment by daxartio** [comment]
Fixed 0.2.0-beta30

**Comment by daxartio** [comment]
Можно отправить запрос без waiting_close
